name: gridsupport
favicon: null
layout_spectrum: 0.9731751577928662
typography_spectrum: 0.5853337321896106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7162188899237663
  lightness: 0.554287395440042
  saturation: 0.7845395940821618
  rhythmicContrast: 0.2399176750332117
purpose: []
