name: gridsupport
favicon: null
layout_spectrum: 0.48902
typography_spectrum: 0.5853337321896106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#ffffff'
    - '#e3b82d'
    - '#8e9892'
    - '#535357'
  brandStrength: 0
  lightness: 0.554287395440042
  saturation: 0.7845395940821618
  rhythmicContrast: 0.2399176750332117
purpose: []
